### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by chuong98** [dksakkos/illumination_augmentation#1]
Hello, thanks for the code. Can you release your checkpoint model for quick testing ?

**Comment by dksakkos** [comment]
Sure, I don't have the original model but I re-trained one with the same settings. You should be reaching an F-Measure of 0.7691 if you set a threshold=0.4 with this one.

https://drive.google.com/file/d/19VxJVc9syahF_bkwtonj9lr-pRmYV1C0/view

**Comment by chuong98** [comment]
awesome, thank you
